<header>
		<div id="google_translate_element"></div><script type="text/javascript">
        function googleTranslateElementInit() {
          new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
        }
    </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
		<div id="header-main">
            <div id="main-logo"><img src="images/logo_main.png" alt="Developer Migration" width="200" /></div>
            <div class="header-links"><a href="about.php">About Us</a></div>
            <div class="header-links"><a href="contact.php">Contact Us</a></div>
			<div class="header-links"><a href="index.php">Home</a></div>
        </div>
</header>
